name: check-sec
on:
  workflow_dispatch:
jobs:
  c:
    runs-on: ubuntu-latest
    steps:
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl secrets list --app applai-backend
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
